<script lang="ts">
  import { workouts } from '$lib/stores';
  import { goto } from '$app/navigation';
  import type { WorkoutDefinition } from '$lib/types';
  import jsyaml from 'js-yaml';
  import { onMount } from 'svelte';

  let yamlText = '';

  onMount(() => {
    const yamlObject = { workouts: $workouts };
    yamlText = jsyaml.dump(yamlObject, { indent: 2, noRefs: true });
  });

  function saveWorkouts() {
    try {
      const data = jsyaml.load(yamlText) as { workouts: WorkoutDefinition[] };
      if (!data || !data.workouts || !Array.isArray(data.workouts)) {
        alert(
          'Invalid YAML format: Expected an object with a "workouts" array containing a list of workouts.'
        );
        return;
      }

      workouts.set(data.workouts);

      goto(`/`);
    } catch (e: any) {
      alert(`Invalid YAML format: ${e.message}`);
    }
  }

  // --- AI Prompt Logic ---
  let promptText = `Please convert this workout plan into the specific YAML format required by my workout app.

The YAML format should follow this structure:

workouts:
  - name: <Name of the Workout>
    rounds:
      - count: <Number of Rounds>
        rest_after_round: <Rest time in seconds>
        exercises:
          - name: <Exercise Name>
            type: <'time' or 'reps'>
            amount: <Time in seconds or number of reps>
            sets: <Number of sets for this exercise>
            rest: <Rest time in seconds between sets>
            notes: <Optional notes for the exercise>

Please ensure the output is only the YAML code block, as I will be pasting it directly into the app.`;

  let buttonText = 'Copy to Clipboard';

  function copyToClipboard() {
    navigator.clipboard.writeText(promptText).then(
      () => {
        buttonText = 'Copied!';
        setTimeout(() => {
          buttonText = 'Copy to Clipboard';
        }, 2000);
      },
      () => {
        alert('Failed to copy prompt to clipboard.');
      }
    );
  }
</script>

<style>
  .container {
    max-width: 800px;
    margin: 2rem auto;
    padding: 1rem;
    font-family: sans-serif;
  }
  h1 {
    color: #333;
    margin-bottom: 0.5rem;
  }
  h2 {
    color: #333;
    margin-top: 2rem;
    margin-bottom: 1rem;
  }
  .container > p {
    color: #555;
    line-height: 1.6;
    margin-bottom: 1.5rem;
  }
  textarea {
    width: 100%;
    height: 500px;
    padding: 0.5rem;
    margin-bottom: 1rem;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    font-family: monospace;
  }
  .actions {
    display: flex;
    gap: 1rem;
  }
  button,
  .button {
    background-color: #007bff;
    color: white;
    padding: 0.75rem 1.25rem;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 1rem;
    text-decoration: none;
    display: inline-block;
    text-align: center;
  }
  button:hover,
  .button:hover {
    background-color: #0056b3;
  }
  .button-cancel {
    background-color: #6c757d;
  }
  .button-cancel:hover {
    background-color: #5a6268;
  }

  .prompt-details {
    border: 1px solid #ddd;
    border-radius: 8px;
    margin: 2rem 0;
  }
  .prompt-details summary {
    padding: 1rem;
    cursor: pointer;
    font-weight: bold;
    color: #0056b3;
  }
  .prompt-content {
    padding: 0 1rem 1rem 1rem;
    border-top: 1px solid #ddd;
  }
  .prompt-content p {
    color: #555;
    line-height: 1.6;
    margin-bottom: 1.5rem;
  }
  .prompt-content pre {
    background-color: #f4f4f4;
    padding: 1rem;
    border-radius: 8px;
    white-space: pre-wrap; /* Allows text to wrap */
    word-wrap: break-word; /* Breaks long words */
    font-family: monospace;
    font-size: 0.95rem;
    border: 1px solid #ddd;
  }
  .prompt-content button {
    background-color: #28a745;
  }
  .prompt-content button:hover {
    background-color: #218838;
  }
</style>

<div class="container">
  <h1>Craft Your Workouts with AI</h1>
  <p>
    Use this page to bulk-edit your workouts in YAML format. This is the perfect place to paste in
    workout plans generated by an AI. Use the prompt below to get started.
  </p>

  <details class="prompt-details">
    <summary>Show AI Prompt for YAML Conversion</summary>
    <div class="prompt-content">
      <p>
        Use the following prompt to ask an AI to convert your free-text workout plan into the YAML
        format our app requires. Simply copy the prompt, paste it into your conversation with the
        AI, and replace the placeholder text with your own plan.
      </p>
      <pre>{promptText}</pre>
      <button on:click={copyToClipboard}>{buttonText}</button>
    </div>
  </details>

  <h2>All Workouts (YAML)</h2>
  <textarea bind:value={yamlText}></textarea>

  <div class="actions">
    <button on:click={saveWorkouts}>Save All Workouts</button>
    <a href="/" class="button button-cancel">Cancel</a>
  </div>
</div>
